services:
  db:
    image: mysql:8.2.0
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: cliente_db


volumes:
  dbase: